use eframe::egui;

pub struct AppTheme {
    pub window_bg: egui::Color32,
    pub window_fg: egui::Color32,
    pub left_panel_bg: egui::Color32,
    pub cell_bg: egui::Color32,
    pub cell_fg: egui::Color32,
    pub label_overlay_bg: egui::Color32,
    pub label_overlay_fg: egui::Color32,
    pub toolbar_bg: egui::Color32,
    pub toolbar_btn_bg: egui::Color32,
    pub toolbar_btn_fg: egui::Color32,
    pub toolbar_btn_press_bg: egui::Color32,
    pub toolbar_btn_hover_bg: egui::Color32,
    pub addres_bar_bg: egui::Color32,
    pub addres_bar_fg: egui::Color32,
    pub btn_hover_bg: egui::Color32,
    pub btn_press_bg: egui::Color32,
    pub reader_bg: egui::Color32,
    pub fav_btn_bg: egui::Color32,
    pub fav_btn_fg: egui::Color32,
    pub library_bg: egui::Color32,
    pub grid_bg: egui::Color32,
    pub lp_btn_bg: egui::Color32,
    pub lp_btn_hover_bg: egui::Color32,
    pub lp_btn_active_bg: egui::Color32,
    pub lp_btn_fg: egui::Color32,
    pub placeholder_bg: egui::Color32,
    pub scroll_bg: egui::Color32,
    pub cell_radius: u8,
    pub cover_radius: f32,
    pub label_overlay_radius: f32,
    pub icon_button_radius: f32,
    pub text_button_radius: f32,
    pub left_panel_button_radius: f32,
    pub settings_tag_radius: f32,
    pub chapter_popup_radius: f32,
    pub address_bar_radius: f32,
    pub toolbar_margin_y: u32,
    pub icon_button_size: f32,
    pub icon_button_font_size: f32,
    pub text_button_font_size: f32,
    pub text_button_padding_x: f32,
    pub text_button_text_offset: f32,
    pub text_button_height: f32,
    pub left_panel_button_height: f32,
    pub left_panel_button_margin: f32,
    pub left_panel_text_offset: f32,
    pub left_panel_font_size: f32,
    pub left_panel_button_spacing: f32,
    pub left_panel_top_padding: f32,
    pub settings_tag_padding_x: f32,
    pub settings_tag_height: f32,
    pub settings_tag_text_offset: f32,
    pub settings_tag_spacing: f32,
    pub seeker_tick_height: f32,
    pub seeker_tick_gap: f32,
    pub seeker_sep_stroke: f32,
    pub seeker_tick_stroke: f32,
    pub seeker_indicator_top: f32,
    pub seeker_indicator_height: f32,
    pub seeker_indicator_half_width: f32,
    pub chapter_popup_margin: u32,
    pub address_bar_margin_x: u32,
    pub address_bar_margin_y: u32,
    pub address_bar_font_size: f32,
    pub mode_badge_size: f32,
    pub mode_badge_offset: f32,
    pub mode_badge_font_size: f32,
    pub seeker_alloc_height: f32,
    pub seeker_inner_height: f32,
    pub row_gap: u8,
}

impl AppTheme {
    pub fn dark() -> Self {
        Self {
            window_bg: egui::Color32::from_rgb(0x0a, 0x0d, 0x12),
            window_fg: egui::Color32::from_rgb(0xcf, 0xd2, 0xd8),
            left_panel_bg: egui::Color32::from_rgb(0x11, 0x11, 0x11),
            cell_bg: egui::Color32::from_rgb(0x22, 0x28, 0x2f),
            cell_fg: egui::Color32::from_rgb(0xcf, 0xd2, 0xd8),
            label_overlay_bg: egui::Color32::from_rgba_unmultiplied(0, 0, 0, 196),
            label_overlay_fg: egui::Color32::from_rgb(0xC4, 0xC4, 0xC4),
            toolbar_bg: egui::Color32::from_rgb(0x0c, 0x0c, 0x0c),
            toolbar_btn_bg: egui::Color32::from_rgba_unmultiplied(0x1a, 0x20, 0x28, 0),
            toolbar_btn_fg: egui::Color32::from_rgb(0xcf, 0xd2, 0xd8),
            toolbar_btn_hover_bg: egui::Color32::from_rgb(0x2f, 0x2f, 0x2f),
            toolbar_btn_press_bg: egui::Color32::from_rgb(0x19, 0x19, 0x19),
            addres_bar_bg: egui::Color32::from_rgb(0x10, 0x10, 0x10),
            addres_bar_fg: egui::Color32::from_rgb(0xcf, 0xd2, 0xd8),
            btn_hover_bg: egui::Color32::from_rgb(0x3f, 0x3f, 0x3f),
            btn_press_bg: egui::Color32::from_rgb(0x19, 0x19, 0x19),
            reader_bg: egui::Color32::BLACK,
            fav_btn_bg: egui::Color32::from_rgba_unmultiplied(0x1a, 0x20, 0x28, 196),
            fav_btn_fg: egui::Color32::from_rgb(0xcf, 0xd2, 0xd8),
            library_bg: egui::Color32::from_rgb(0x0c, 0x0c, 0x0c),
            grid_bg: egui::Color32::from_rgb(0x0c, 0x0c, 0x0c),
            lp_btn_bg: egui::Color32::from_rgb(0x2a, 0x2a, 0x2a),
            lp_btn_hover_bg: egui::Color32::from_rgb(0x3f, 0x3f, 0x3f),
            lp_btn_active_bg: egui::Color32::from_rgb(0x19, 0x19, 0x19),
            lp_btn_fg: egui::Color32::from_rgb(0xc4, 0xc4, 0xc4),
            placeholder_bg: egui::Color32::from_rgb(0x15, 0x15, 0x15),
            scroll_bg: egui::Color32::from_rgb(0x10, 0x10, 0x10),
            cell_radius: 10,
            cover_radius: 10.0,
            label_overlay_radius: 10.0,
            icon_button_radius: 8.0,
            text_button_radius: 6.0,
            left_panel_button_radius: 6.0,
            settings_tag_radius: 6.0,
            chapter_popup_radius: 6.0,
            address_bar_radius: 8.0,
            toolbar_margin_y: 4,
            icon_button_size: 32.0,
            icon_button_font_size: 16.0,
            text_button_font_size: 14.0,
            text_button_padding_x: 12.0,
            text_button_text_offset: 6.0,
            text_button_height: 28.0,
            left_panel_button_height: 40.0,
            left_panel_button_margin: 10.0,
            left_panel_text_offset: 15.0,
            left_panel_font_size: 16.0,
            left_panel_button_spacing: 4.0,
            left_panel_top_padding: 20.0,
            settings_tag_padding_x: 20.0,
            settings_tag_height: 28.0,
            settings_tag_text_offset: 8.0,
            settings_tag_spacing: 4.0,
            seeker_tick_height: 7.0,
            seeker_tick_gap: 1.5,
            seeker_sep_stroke: 1.0,
            seeker_tick_stroke: 2.0,
            seeker_indicator_top: 2.0,
            seeker_indicator_height: 5.0,
            seeker_indicator_half_width: 3.0,
            chapter_popup_margin: 4,
            address_bar_margin_x: 8,
            address_bar_margin_y: 9,
            address_bar_font_size: 14.0,
            mode_badge_size: 22.0,
            mode_badge_offset: 4.0,
            mode_badge_font_size: 12.0,
            seeker_alloc_height: 20.0,
            seeker_inner_height: 16.0,
            row_gap: 8,
        }
    }

    pub fn flexoki() -> Self {
        Self {
            window_bg: egui::Color32::from_rgb(0x10, 0x0F, 0x0F),
            window_fg: egui::Color32::from_rgb(0xCE, 0xCD, 0xC3),
            left_panel_bg: egui::Color32::from_rgb(0x1C, 0x1B, 0x1A),
            cell_bg: egui::Color32::from_rgb(0x28, 0x27, 0x26),
            cell_fg: egui::Color32::from_rgb(0xCE, 0xCD, 0xC3),
            label_overlay_bg: egui::Color32::from_rgba_unmultiplied(0, 0, 0, 196),
            label_overlay_fg: egui::Color32::from_rgb(0xCE, 0xCD, 0xC3),
            toolbar_bg: egui::Color32::from_rgb(0x10, 0x0F, 0x0F),
            toolbar_btn_bg: egui::Color32::from_rgba_unmultiplied(0, 0, 0, 0),
            toolbar_btn_fg: egui::Color32::from_rgb(0xCE, 0xCD, 0xC3),
            toolbar_btn_hover_bg: egui::Color32::from_rgba_unmultiplied(40, 39, 38, 196),
            toolbar_btn_press_bg: egui::Color32::from_rgb(0x10, 0x0F, 0x0F),
            addres_bar_bg: egui::Color32::from_rgba_unmultiplied(0, 0, 0, 0),
            addres_bar_fg: egui::Color32::from_rgb(0xCE, 0xCD, 0xC3),
            btn_hover_bg: egui::Color32::from_rgb(0x34, 0x33, 0x31),
            btn_press_bg: egui::Color32::from_rgb(0x28, 0x27, 0x26),
            reader_bg: egui::Color32::from_rgb(0x10, 0x0F, 0x0F),
            fav_btn_bg: egui::Color32::from_rgba_unmultiplied(28, 27, 26, 196),
            fav_btn_fg: egui::Color32::from_rgb(0xCE, 0xCD, 0xC3),
            library_bg: egui::Color32::from_rgb(0x10, 0x0F, 0x0F),
            grid_bg: egui::Color32::from_rgb(0x10, 0x0F, 0x0F),
            lp_btn_bg: egui::Color32::from_rgb(0x28, 0x27, 0x26),
            lp_btn_hover_bg: egui::Color32::from_rgba_unmultiplied(52, 51, 49, 196),
            lp_btn_active_bg: egui::Color32::from_rgb(0x1C, 0x1B, 0x1A),
            lp_btn_fg: egui::Color32::from_rgb(0xCE, 0xCD, 0xC3),
            placeholder_bg: egui::Color32::from_rgb(0x1C, 0x1B, 0x1A),
            scroll_bg: egui::Color32::from_rgb(0x10, 0x0F, 0x0F),
            cell_radius: 10,
            cover_radius: 10.0,
            label_overlay_radius: 8.0,
            icon_button_radius: 8.0,
            text_button_radius: 6.0,
            left_panel_button_radius: 6.0,
            settings_tag_radius: 6.0,
            chapter_popup_radius: 6.0,
            address_bar_radius: 8.0,
            toolbar_margin_y: 4,
            icon_button_size: 32.0,
            icon_button_font_size: 16.0,
            text_button_font_size: 14.0,
            text_button_padding_x: 12.0,
            text_button_text_offset: 6.0,
            text_button_height: 28.0,
            left_panel_button_height: 40.0,
            left_panel_button_margin: 10.0,
            left_panel_text_offset: 15.0,
            left_panel_font_size: 16.0,
            left_panel_button_spacing: 4.0,
            left_panel_top_padding: 20.0,
            settings_tag_padding_x: 20.0,
            settings_tag_height: 28.0,
            settings_tag_text_offset: 8.0,
            settings_tag_spacing: 4.0,
            seeker_tick_height: 7.0,
            seeker_tick_gap: 1.5,
            seeker_sep_stroke: 1.0,
            seeker_tick_stroke: 2.0,
            seeker_indicator_top: 2.0,
            seeker_indicator_height: 5.0,
            seeker_indicator_half_width: 3.0,
            chapter_popup_margin: 4,
            address_bar_margin_x: 8,
            address_bar_margin_y: 9,
            address_bar_font_size: 14.0,
            mode_badge_size: 22.0,
            mode_badge_offset: 4.0,
            mode_badge_font_size: 12.0,
            seeker_alloc_height: 20.0,
            seeker_inner_height: 16.0,
            row_gap: 6,
        }
    }

    pub fn apply_to_ctx(&self, ctx: &egui::Context) {
        let mut style = (*ctx.style()).clone();
        style.visuals.window_fill = self.window_bg;
        style.visuals.extreme_bg_color = self.cell_bg;
        style.visuals.override_text_color = Some(self.window_fg);
        ctx.set_style(style);
    }
}
